jasypt:
  encryptor:
    password: ${ENCRPYTOR_PASSWORD}

spring:
  profiles:
    active: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always

  # API 호출시, SQL 문을 콘솔에 출력한다
  jpa:
    show-sql: true

    hibernate:
      ddl-auto: create-drop

    # MySQL 을 사용할 것.
    database: mysql

    properties:
      hibernate:
        format_sql: true

    open-in-view: false

github:
  client-id: e75bd1cffaa68832aac4
  client-secret: ENC(KiLD337Md1ythVW78LXB1B/cQNzNAykOSpPdvLiyaPIFAYgXFJ55uYoz4KFpabWPNqCjuhxPXKvbzoJb0LxpWcw3LpMcbcid0EEw56uFX7E=)
  code-url: https://github.com/login/oauth/authorize
  user-api-url: https://api.github.com/user
  access-token-url: https://github.com/login/oauth/access_token

jwt:
  key: ENC(LN67HOkUC8A4I9n7BVfOyjHzjkpgL9UieVI/HZOY8pPZ/7uYI5a2Ssfie8YGqFyGhWPleM9lFZFd/GjaC6+DZw==)
---
spring:
  profiles: local

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

logging:
  level:
    sql: debug
    root: info
    com:
      codesquad:
        issuetracker: debug
---
spring:
  profiles: production

  datasource:
    url: ENC(xwiWLpHJ7FJPLtOs2pDeyPhXmREXndlkwS1TUniPX4wzZUtU6Jz114Ltm84Hzg4gR1LdnFEe2CPJQ/TxIvUa1/sr1GB38j0wkYo8p4PyNUzAXAs5vRszxHmk41IdEujZRpllGl+fZe5OPo97shn7dfwvB4mUQunTmik76o2JjrQRwMSE1CnyjjV8PXD1XqvmXB9yLNVkiox8MBrNTddw6A==)
    username: ENC(dWFI/DAXSod1mpm9fOEXhd70DB1D8lOmuYHCA/z7y0CfA5k699XdBzzNQLw5ewHN)
    password: ENC(kBF9VO2QdavUtJyL2oUkx/vjv+AyevUXEQZ5ZCpvDVk5fU7IpGtg5e/R4kh69YeA)

logging:
  level:
    sql: debug
    root: info
    com:
      codesquad:
        issuetracker: debug
