version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/issue-tracker/BE
permissions:
  - object: /home/ubuntu/issue-tracker/BE
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  AfterInstall:
    - location: deploy-be.sh
      timeout: 60
      runas: root
