# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CD with Node.js

on:
  push:
    branches: [ dev, master ]

env:
    PROJECT_NAME: issue-tracker-08

jobs:
  build:
    name: deploy

    runs-on: ubuntu-16.04

    defaults:
      run:
        shell: bash
        working-directory: FE

    strategy:
      matrix:
        node-version: [ 12.x ]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm install

    - run: npm run build
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Upload to S3
      run: aws deploy push --application-name codesquad-app --s3-location s3://codesquad-ever/$PROJECT_NAME/build-fe.zip --source .

    - name: Code Deploy
      run: aws deploy create-deployment --application-name codesquad-app --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name FE-DeployGroup --s3-location bucket=codesquad-ever,bundleType=zip,key=$PROJECT_NAME/build-fe.zip
